[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
name = "ros_quick_gui"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
dependencies = [
  "PyQt5",
  "rclpy",
  "rosidl_runtime_py",
]

[project.scripts]
ros-quick-gui = "ros_quick_gui.core.main:entry"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.isort]
line_length = 160
lines_between_sections = 0

[tool.black]
line-length = 160
